import { test, expect } from '@playwright/test'
test('리드 인테이크 임시저장 새로고침 유지', async ({ page }) => {
  test.setTimeout(60_000)
  await page.goto('/lead-intake'); await expect(page).not.toHaveURL(/\/login/, { timeout: 15_000 })
  await page.evaluate(() => Object.keys(localStorage).filter(k => k.startsWith('draft:v1:')).forEach(k => localStorage.removeItem(k)))
  const ta = page.locator('textarea').first()
  await ta.fill('리드 임시저장 검증 — 삼성SDS 김철수 부장')
  await page.waitForTimeout(800)
  const saved = await page.evaluate(() => Object.keys(localStorage).find(k => k.includes('lead-intake')))
  expect(saved).toBeTruthy()
  await page.reload()
  await expect(page.getByTestId('draft-restore-banner')).toBeVisible({ timeout: 15_000 })
  await page.getByTestId('draft-restore-btn').click()
  await expect(page.locator('textarea').first()).toHaveValue(/삼성SDS/)
  await page.evaluate(() => Object.keys(localStorage).filter(k => k.startsWith('draft:v1:')).forEach(k => localStorage.removeItem(k)))
})
